### ISSUE TITLE
콜라보레이터 초대 확인

### ISSUE THREAD

**Issue by isume** [isume/OSSdev_T4#3]
콜라보레이터 초대가 깃헙 계정으로 등록된 이메일로 전송됬을겁니다. 꼭 확인해주세요.

만약 이메일의 초대링크를 확인하고 난 후에도 잘 모르겠다면 이 리포지터리를 클론한 후 check_username.txt파일을 생성해 check_invite 브랜치로 푸시하는걸로 확인하셔도 좋습니다.

**Comment by kikyo424** [comment]
확인했습니다.
